FROM ubuntu:latest

# Set non-interactive mode for installations
ENV DEBIAN_FRONTEND=noninteractive

# Install apt dependencies
RUN apt-get update
RUN apt-get install -y curl git unzip xz-utils zip libglu1-mesa
RUN apt-get install -y clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev ghostscript g++ xorg-dev libgles2-mesa-dev libdbus-1-dev libhdf5-dev sqlite3 libsqlite3-dev
RUN apt-get clean

# Install Flutter
RUN git clone https://github.com/flutter/flutter.git /opt/flutter --branch stable
ENV PATH="/opt/flutter/bin:/root/.pub-cache/bin:$PATH"
RUN flutter doctor

WORKDIR /app

# Default command: open a shell
CMD ["/bin/bash"]
